import { crewSkill } from '../../systems/stats.js';
import { CREW, EQUIPMENT } from '../../data/catalog.js';
import { UI, text } from '../../data/ui.js';
import { heading, art, button, stat, sectionTitle, meter, price, number } from '../components.js';

export function renderCrew(state,d) {
  const roleKeys=['navigator','accountant','gunner','doctor'];
  return `${heading(UI.crewTitle,UI.crewSub)}<div class="panel journal-stats"><div class="stats-grid">${Object.entries(UI.skills).map(([key,label])=>stat(label,Math.round(d.skills[key]))).join('')}</div><p class="hint">${UI.roleHint}</p></div><div class="card-grid">${state.crew.map(member=>{
    const crew=CREW[member.id],level=1+Math.floor(member.xp/100);
    return `<article class="card crew-card"><div class="crew-portrait">${art(crew.asset,crew.name)}<span class="badge gold">${UI.roles[member.role||'reserve']}</span></div><div class="crew-detail"><div class="row spread"><h3>${crew.name}</h3><span class="badge dim">${text('level',{n:level})}</span></div><p class="crew-title">${crew.title}</p><p>${crew.description}</p><div class="crew-skills">${Object.entries(UI.skills).map(([key,label])=>{const score=crewSkill(member,key);return `<div class="crew-skill"><div><span>${label}</span><strong>${score}</strong></div>${meter(score,150,key==='combat'?'red':'')}</div>`;}).join('')}</div><div class="row spread small muted"><span>${UI.experience}</span><span>${member.xp%100} / 100</span></div>${meter(member.xp%100,100,'blue')}<div class="crew-selects"><label>${UI.assignment}<select data-action="assign" data-crew-id="${member.id}" ${member.role==='captain'||!state.portId?'disabled':''}>${member.role==='captain'?`<option value="captain">${UI.roles.captain}</option>`:`<option value="">${UI.roles.reserve}</option>${roleKeys.map(role=>`<option value="${role}" ${member.role===role?'selected':''}>${UI.roles[role]}</option>`).join('')}`}</select></label><label>${UI.equipment}<select data-action="equip" data-crew-id="${member.id}" ${!state.portId?'disabled':''}><option value="">${UI.noEquipment}</option>${Object.values(EQUIPMENT).filter(e=>state.equipment[e.id]>0||member.equipment===e.id).map(e=>`<option value="${e.id}" ${member.equipment===e.id?'selected':''}>${e.name} · ${e.description}</option>`).join('')}</select></label></div></div></article>`;
  }).join('')}</div><section class="ship-shop">${sectionTitle(UI.equipmentShop)}<div class="equipment-grid">${Object.values(EQUIPMENT).map(e=>`<article class="card equipment-card">${art(e.asset,e.name)}<div><h3>${e.name}</h3><p>${e.description}</p><small>${UI.inventory} ${state.equipment[e.id]||0}</small><br>${button(`${UI.buy} · ${price(e.price)}`,'game',{type:'buyEquipment','equipment-id':e.id},'outline',!state.portId||state.gold<e.price)}</div></article>`).join('')}</div></section>`;
}
