import { SHIP_TYPES } from '../../data/catalog.js';
import { UI, text } from '../../data/ui.js';
import { heading, art, button, icon, meter, stat, number, sectionTitle, price } from '../components.js';

export function renderFleet(state,d) {
  return `${heading(UI.fleetTitle,UI.fleetSub)}<div class="panel journal-stats"><div class="stats-grid">${stat(UI.fleetTitle,text('fleetCount',{n:state.fleet.length}))}${stat(UI.cargo,`${d.cargoUsed} / ${d.cargoCapacity}`)}${stat(UI.firepower,number(d.firepower))}</div></div><div class="card-grid">${state.fleet.map((ship,i)=>{
    const type=SHIP_TYPES[ship.type],stats=d.ships.find(s=>s.id===ship.id);
    return `<article class="card ship-card"><div class="card-title"><h3>${ship.name}</h3><span class="badge ${i===0?'gold':''}">${i===0?UI.flagship:UI.escort}</span></div>${art(type.asset,type.name)}<div class="row spread small"><span>${type.name}</span><span class="muted">${UI.hull} ${ship.hull} / ${stats.maxHull}</span></div>${meter(ship.hull,stats.maxHull,'green')}<div class="stats-grid">${stat(UI.sailors,`${ship.sailors}/${stats.maxSailors}`)}${stat(UI.knots,stats.speed.toFixed(1))}${stat(UI.capacity,stats.cargoCapacity)}${stat(UI.firepower,stats.firepower)}${stat(UI.supplyCapacity,stats.supplyCapacity)}${stat(UI.slots,type.slots)}</div><div class="card-actions">${button(UI.nav[3].name,'ship-cabins',{'ship-id':ship.id},'outline')}${button(`${UI.upgradeSails} ${ship.sails}/3 · ${price((ship.sails+1)*1200)}`,'game',{type:'upgrade','ship-id':ship.id,upgrade:'sails'},'',!state.portId||ship.sails>=3)}${button(`${UI.upgradeArmor} ${ship.armor}/3 · ${price((ship.armor+1)*1200)}`,'game',{type:'upgrade','ship-id':ship.id,upgrade:'armor'},'',!state.portId||ship.armor>=3)}${state.fleet.length>1?button(UI.sellShip,'sell-ship',{'ship-id':ship.id},'danger',!state.portId):''}</div></article>`;
  }).join('')}</div><section class="ship-shop">${sectionTitle(UI.shipMarket,state.portId?button(UI.repairAll,'game',{type:'repair'},'outline'): '')}<div class="ship-shop-grid">${Object.values(SHIP_TYPES).map(ship=>`<article class="ship-shop-card">${art(ship.asset,ship.name)}<h3>${ship.name}</h3><p>${ship.description}</p><div class="ship-price">${price(ship.price)}</div><div class="small muted">${UI.hull} ${ship.hull} · ${UI.slots} ${ship.slots}</div>${button(UI.buyShip,'game',{type:'buyShip','ship-type':ship.id},'outline',!state.portId||state.gold<ship.price||state.fleet.length>=5)}</article>`).join('')}</div></section>`;
}
